Repository OneIdea-IRNITU/Smart-schedule-IRNITU, pull requests merged in 2021-04, with the labels that each got.

#141 Функционал экзаменов
  functions_api/functions/creating_schedule.py
  getting_schedule/functions/exams_storage.py
  getting_schedule/functions/get_exams.py
  getting_schedule/main.py
  tg_bot/actions/main_menu/schedule.py
  tg_bot/tg_bot.py
  tg_bot/tools/keyboards.py
  tg_bot/tools/storage.py
  vk_bot/API/functions_api.py
  vk_bot/actions/main_menu/schedule.py
  vk_bot/tools/keyboards.py
  vk_bot/tools/storage.py
  vk_bot/vk_bot.py
Labels: bug-fix, enhancement

#147 Добавить функцию просмотра расписания экзаменов.
  functions_api/app.py
  functions_api/functions/creating_schedule.py
  getting_schedule/functions/exams_storage.py
  getting_schedule/functions/logger.py
  getting_schedule/functions/mongo_storage.py
  getting_schedule/main.py
  getting_schedule/requirements.txt
  tg_bot/actions/main_menu/schedule.py
  tg_bot/tools/storage.py
  vk_bot/API/functions_api.py
  vk_bot/actions/main_menu/schedule.py
  vk_bot/tools/storage.py
Labels: bug-fix

#149 Добавить функцию в functions_api
  tg_bot/API/functions_api.py
Labels: bug-fix

#150 Исправить ошибку с выводом при отсутствии расписания экзаменов
  tg_bot/actions/main_menu/schedule.py
  vk_bot/API/functions_api.py
  vk_bot/actions/main_menu/schedule.py
  vk_bot/tools/schedule_processing.py
Labels: bug-fix, enhancement

#151 Исправить цвет клавиатуры Экзаменов
  vk_bot/tools/keyboards.py
Labels: invalid

#152 Запуск функции напоминаний каждые 60 секунд
  notification_service/reminder.py
Labels: enhancement, refactoring

#153 Поиск по экзаменам
  tg_bot/actions/search/aud_search.py
  tg_bot/actions/search/prep_and_group_search.py
  tg_bot/tg_bot.py
  tg_bot/tools/keyboards.py
  tg_bot/tools/storage.py
  vk_bot/actions/main_menu/schedule.py
  vk_bot/actions/registration/student_registration.py
  vk_bot/actions/search/aud_search.py
  vk_bot/actions/search/prep_and_group_search.py
  vk_bot/tools/keyboards.py
  vk_bot/tools/storage.py
Labels: enhancement

#158 Dependabot
  .github/workflows/deploy.yml
  notification_service/requirements.txt
  vk_bot/requirements.txt
Labels: refactoring

#160 Скрипт для массового оповещения пользователей ВК и ТГ.
  tg_bot/script_release_tg.py
  tg_bot/tools/storage.py
  vk_bot/script_release_vk.py
  vk_bot/tools/storage.py
Labels: enhancement

#161 Скрипт для массовой рассылки пользователям ВК и ТГ.
  tg_bot/script_release_tg.py
  tg_bot/tools/storage.py
  vk_bot/script_release_vk.py
  vk_bot/tools/storage.py
Labels: enhancement

#162 Хот-фикс
  functions_api/functions/creating_schedule.py
  tg_bot/script_release_tg.py
  vk_bot/actions/registration/student_registration.py
  vk_bot/actions/search/prep_and_group_search.py
  vk_bot/script_release_vk.py
  vk_bot/tools/keyboards.py
Labels: bug-fix

#163 Корректировки в README and .example
  .env.example
  README.md
Labels: bug-fix

#164 Хот фикс
  .env.example
  README.md
  functions_api/functions/creating_schedule.py
  tg_bot/script_release_tg.py
  vk_bot/actions/registration/student_registration.py
  vk_bot/actions/search/prep_and_group_search.py
  vk_bot/script_release_vk.py
  vk_bot/tools/keyboards.py
Labels: bug-fix

#165 Пофиксить баги с СМ-19-1
  tg_bot/actions/search/prep_and_group_search.py
  vk_bot/actions/search/prep_and_group_search.py
Labels: bug-fix

#166 Обернуть bot.infinity_polling в бесконечный цикл
  tg_bot/tg_bot.py
Labels: bug-fix

#167 Пофиксить ошибку с Основным меню в поиске преподов
  tg_bot/actions/search/prep_and_group_search.py
Labels: bug-fix

#169 Пофиксить экзамены в вк
  vk_bot/actions/search/prep_and_group_search.py
Labels: bug-fix

#170 Develop
  functions_api/functions/creating_schedule.py
  tg_bot/actions/search/prep_and_group_search.py
  tg_bot/tg_bot.py
  vk_bot/actions/search/prep_and_group_search.py
Labels: bug-fix
