Repository OneIdea-IRNITU/Smart-schedule-IRNITU, pull requests merged in 2021-02, with the labels that each got.

#89 Исправить: некорректный вывод ближайшей пары
  vk_bot/actions/main_menu/schedule.py
Labels: Prerelease, bug

#91 Пофиксить баг на этапе выбора института и обновление клавиатуры при неправильном вводе.
  vk_bot/actions/registration/student_registration.py
Labels: bug

#97 Исправить уведомления в ботах
  docker-compose.yaml
  notification_service/reminder.py
  notification_service/reminders_tg.py
  notification_service/reminders_vk.py
  notification_service/requirements.txt
  notification_service/start_reminders.py
  notification_service/storage.py
  notification_service/tests/test_reminder.py
  notification_service/tests/test_tools.py
  notification_service/tools/__init__.py
  vk_bot/requirements.txt
Labels: Prerelease, bug, refactoring

#99 Исправить напоминания
  docker-compose.yaml
  notification_service/reminder.py
  notification_service/reminders_tg.py
  notification_service/reminders_vk.py
  notification_service/requirements.txt
  notification_service/start_reminders.py
  notification_service/tests/test_reminder.py
  notification_service/tests/test_tools.py
  notification_service/tools/__init__.py
  notification_service/tools/logger.py
  notification_service/tools/storage.py
  vk_bot/requirements.txt
  web_manager/run.sh
Labels: bug, refactoring

#103 Обработка получения расписания
  notification_service/reminder.py
Labels: Prerelease, bug

#104 Рефакторинг docker-compose. Исправить ошибки уведомлений
  .env.example
  docker-compose.yaml
  notification_service/reminder.py
  parser/Dockerfile
  parser/parser.py
  parser/requirements.txt
  parser/storage.py
  tg_bot/Dockerfile
  tg_bot/requirements.txt
  tg_bot/run.sh
  tg_bot/tg_bot.py
  tg_bot/wsgi.py
Labels: bug, refactoring

#105 Создание volume в папке с проектом
  docker-compose.yaml
Labels: enhancement, refactoring

#108 Инструкция по запуску проекта
  README.md
Labels: documentation

#110 Удалить web manager и nginx
  docker-compose.yaml
  nginx/Dockerfile
  nginx/nginx.conf
  web_manager/.DS_Store
  web_manager/Dockerfile
  web_manager/app/.DS_Store
  web_manager/app/__init__.py
  web_manager/app/bots/__init__.py
  web_manager/app/bots/tg_bot.py
  web_manager/app/forms.py
  web_manager/app/static/.DS_Store
  web_manager/app/static/css/style.css
  web_manager/app/static/img/av.gif
  web_manager/app/static/img/off.jpg
  web_manager/app/static/img/on.jpg
  web_manager/app/static/js/get_status.js
  web_manager/app/storage.py
  web_manager/app/templates/admin/analytics_index.html
  web_manager/app/templates/admin/index.html
  web_manager/app/templates/admin/tg_bot/send_message.html
  web_manager/app/views.py
  web_manager/requirements.txt
  web_manager/run.sh
  web_manager/wsgi.py
Labels: refactoring

#111 Поиск и регистрация преподавателей в tg боте
  tg_bot/actions/main_menu/schedule.py
  tg_bot/actions/registration/teacher_registration.py
  tg_bot/actions/search/__init__.py
  tg_bot/actions/search/aud_search.py
  tg_bot/actions/search/prep_and_group_search.py
  tg_bot/functions/storage.py
  tg_bot/requirements.txt
  tg_bot/tg_bot.py
  tg_bot/tools/keyboards.py
  tg_bot/tools/schedule_processing.py
  vk_bot/actions/search/aud_search.py
  vk_bot/actions/search/prep_and_group_search.py
  vk_bot/tools/keyboards.py
Labels: enhancement

#113 Обработка нижнего регистра команд
  vk_bot/vk_bot.py
Labels: invalid

#116 Отдельный сервис functions_api
  docker-compose.yaml
  functions_api/Dockerfile
  functions_api/app.py
  functions_api/functions/__init__.py
  functions_api/functions/creating_schedule.py
  functions_api/functions/find_week.py
  functions_api/functions/near_lesson.py
  functions_api/functions/notifications.py
  functions_api/requirements.txt
  functions_api/run.sh
  functions_api/wsgi.py
  tg_bot/API/__init__.py
  tg_bot/API/functions_api.py
  tg_bot/actions/main_menu/reminders.py
  tg_bot/actions/main_menu/schedule.py
  tg_bot/actions/registration/student_registration.py
  tg_bot/actions/search/aud_search.py
  tg_bot/actions/search/prep_and_group_search.py
  tg_bot/functions/calculating_reminder_times.py
  tg_bot/functions/find_week.py
  tg_bot/tg_bot.py
  tg_bot/tools/logger.py
  tg_bot/tools/schedule_processing.py
  tg_bot/tools/storage.py
  vk_bot/API/__init__.py
  vk_bot/API/functions_api.py
  vk_bot/Dockerfile
  vk_bot/actions/main_menu/reminders.py
  vk_bot/actions/main_menu/schedule.py
  vk_bot/actions/search/aud_search.py
  vk_bot/actions/search/prep_and_group_search.py
  vk_bot/functions/creating_schedule.py
  vk_bot/functions/near_lesson.py
  vk_bot/functions/notifications.py
  vk_bot/tools/logger.py
  vk_bot/tools/schedule_processing.py
  vk_bot/tools/storage.py
  vk_bot/vk_bot.py
Labels: enhancement, refactoring

#117 Исправили баг с нотификатором для преп и пофиксили напоминалку
  tg_bot/actions/main_menu/reminders.py
  tg_bot/tg_bot.py
Labels: bug-fix

#120 Обновление напоминаний при смене расписания
  docker-compose.yaml
  notification_service/API/__init__.py
  notification_service/API/functions_api.py
  notification_service/start_reminders.py
  notification_service/tools/reminder_updater.py
  notification_service/tools/storage.py
Labels: bug-fix, enhancement

#121 Анализатор уязвимостей кода
  .github/workflows/codeql-analysis.yml
Labels: enhancement

#123 Добавлена Подсказка по использованию чат-ботов, переработана команда Помощь
  tg_bot/actions/commands.py
  tg_bot/actions/registration/student_registration.py
  tg_bot/actions/registration/teacher_registration.py
  tg_bot/tg_bot.py
  vk_bot/actions/commands.py
  vk_bot/actions/main_menu/main_menu.py
  vk_bot/actions/registration/student_registration.py
  vk_bot/actions/registration/teacher_registration.py
  vk_bot/tools/keyboards.py
  vk_bot/vk_bot.py
Labels: enhancement
