Repository OneIdea-IRNITU/Smart-schedule-IRNITU, pull requests merged in 2021-03, with the labels that each got.

#128 Повышение безопасности. Исправление бага "Мутирование в полночь"
  functions_api/functions/find_week.py
  vk_bot/actions/main_menu/main_menu.py
  vk_bot/actions/registration/student_registration.py
  vk_bot/tools/keyboards.py
  vk_bot/vk_bot.py
Labels: bug-fix

#133 Вызов команд с помощью ручного ввода
  vk_bot/vk_bot.py
Labels: bug-fix

#131 Инструкции для пользователя, исправлена кнопка "Помощь" вместо "Список команд"
  tg_bot/tg_bot.py
  tg_bot/tools/keyboards.py
Labels: bug, bug-fix, user interface

#134 Создание подключений к бд для каждого объекта напоминалки
  notification_service/reminder.py
  notification_service/start_reminders.py
  notification_service/tools/reminder_updater.py
Labels: bug-fix, refactoring

#139 Проверка, что расписание пользователя существует
  notification_service/tools/reminder_updater.py
Labels: bug, refactoring
