Repository OneIdea-IRNITU/Smart-schedule-IRNITU, pull requests merged in 2021-01, with the labels that each got.

#26 Features/nginx to docker
  .gitignore
  docker-compose.yaml
  nginx/Dockerfile
  nginx/nginx.conf
Labels: enhancement

#34 Проверка CI при reopened pull request
  .github/workflows/checkers.yml
Labels: bug

#37 Update checkers.yml
  .github/workflows/checkers.yml
Labels: bug

#41 Tg and vk are one
  Bot_vk/VK_BOT_main.py
  Bot_vk/functions/creating_schedule.py
  Bot_vk/functions/near_lesson.py
  tg_bot/bot.py
  tg_bot/functions/creating_buttons.py
  tg_bot/functions/creating_schedule.py
  tg_bot/functions/near_lesson.py
Labels: bug

#44 Develop
  Bot_vk/VK_BOT_main.py
  Bot_vk/functions/creating_schedule.py
  Bot_vk/functions/near_lesson.py
  tg_bot/bot.py
  tg_bot/functions/creating_buttons.py
  tg_bot/functions/creating_schedule.py
  tg_bot/functions/near_lesson.py
Labels: enhancement

#47 Установка переменных окружения для сервиса getting_schedule
  .github/workflows/deploy.yml
Labels: enhancement

#48 Исправлена опечатка: не было "secrets." при импорте переменных
  .github/workflows/deploy.yml
Labels: bug

#50 Features/getting schedule
  docker-compose.yaml
  getting_schedule/Dockerfile
  getting_schedule/data_conversion.py
  getting_schedule/main.py
  getting_schedule/mongo_storage.py
  getting_schedule/postgre_storage.py
  getting_schedule/requirements.txt
  getting_schedule/tests/test_data_conversion.py
Labels: enhancement

#51 Develop
  docker-compose.yaml
  getting_schedule/Dockerfile
  getting_schedule/data_conversion.py
  getting_schedule/main.py
  getting_schedule/mongo_storage.py
  getting_schedule/postgre_storage.py
  getting_schedule/requirements.txt
  getting_schedule/tests/test_data_conversion.py
Labels: enhancement

#55 Features/getting schedule
  docker-compose.yaml
  getting_schedule/data_conversion.py
  getting_schedule/functions/__init__.py
  getting_schedule/functions/mongo_storage.py
  getting_schedule/functions/postgre_storage.py
  getting_schedule/functions/schedule_tools.py
  getting_schedule/main.py
  getting_schedule/requirements.txt
  getting_schedule/tests/test_data_conversion.py
Labels: enhancement

#60 Регистрация преподавателей в ВК и поиск по группам и преподавателям
  Bot_vk/VK_BOT_main.py
  Bot_vk/functions/creating_schedule.py
  Bot_vk/functions/logger.py
  Bot_vk/functions/storage.py
  Bot_vk/requirements.txt
  notification_service/start_reminders.py
Labels: enhancement

#61 Иправить ошибку с совпадением имен функции и глобальной переменной
  Bot_vk/VK_BOT_main.py
Labels: bug

#62 Вынести формирование всех клавиатур из VK_Bot в отдельный файл
  Bot_vk/VK_BOT_main.py
  Bot_vk/keyboards.py
Labels: refactoring

#66 Поиск по аудиториям
  Bot_vk/VK_BOT_main.py
  Bot_vk/functions/creating_schedule.py
  Bot_vk/functions/storage.py
  Bot_vk/keyboards.py
Labels: enhancement

#83 Подготовить клавиатуру под старую версию
  vk_bot/tools/keyboards.py
Labels: Prerelease

#84 Refactoring/tg bot
  tg_bot/actions/__init__.py
  tg_bot/actions/commands.py
  tg_bot/actions/main_menu/__init__.py
  tg_bot/actions/main_menu/main_menu.py
  tg_bot/actions/main_menu/reminders.py
  tg_bot/actions/main_menu/schedule.py
  tg_bot/actions/registration/__init__.py
  tg_bot/actions/registration/student_registration.py
  tg_bot/bot.py
  tg_bot/functions/creating_schedule.py
  tg_bot/functions/notifications.py
  tg_bot/run.sh
  tg_bot/tools/__init__.py
  tg_bot/tools/check_schedule.py
  tg_bot/tools/get_text_schedule_not_available.py
  tg_bot/tools/keyboards.py
  tg_bot/tools/statistics.py
Labels: refactoring

#87 Пофиксить неправильный вывод основного расписания
  tg_bot/functions/creating_schedule.py
Labels: Prerelease, bug
